export type VocabItem = { id: number; word: string; phonetic: string; partOfSpeech: string; meaning: string; note: string };

export const vocabulary: VocabItem[] = [
  { id: 4151, word: "combat", phonetic: "/ˈkɒmbæt/", partOfSpeech: "v.", meaning: "打擊；競鬥", note: "combat + crime / terrorism / inflation：對抗犯罪、恐怖主義、通貨膨脹" },
  { id: 4152, word: "comedian", phonetic: "/kəˈmiːdiən/", partOfSpeech: "n.", meaning: "單口喜劇演員；喜劇演員", note: "a stand-up comedian：單口喜劇演員" },
  { id: 4153, word: "commentary", phonetic: "/ˈkɒməntri/", partOfSpeech: "n.", meaning: "評論", note: "a commentary on sth.：我對某事的評論" },
  { id: 4154, word: "commission", phonetic: "/kəˈmɪʃən/", partOfSpeech: "n.", meaning: "佣金；委託", note: "用法：委託；佣金" },
  { id: 4155, word: "commitment", phonetic: "/kəˈmɪtmənt/", partOfSpeech: "n.", meaning: "承諾；奉獻", note: "make a commitment：作出承諾" },
  { id: 4156, word: "commodity", phonetic: "/kəˈmɒdəti/", partOfSpeech: "n.", meaning: "商品", note: "merchandise = goods" },
  { id: 4157, word: "communism", phonetic: "/ˈkɒmjʊnɪzəm/", partOfSpeech: "n.", meaning: "共產主義", note: "communist n.：共產黨者" },
  { id: 4158, word: "commute", phonetic: "/kəˈmjuːt/", partOfSpeech: "vi.", meaning: "通勤", note: "commuter n.：通勤者" },
  { id: 4159, word: "compact", phonetic: "/kəmˈpækt/", partOfSpeech: "adj.", meaning: "小型的；小的", note: "miniature：小型的" },
  { id: 4160, word: "comparable", phonetic: "/ˈkɒmpərəbəl/", partOfSpeech: "adj.", meaning: "可比較的", note: "comparable to / with sb. / sth.；incomparable：無與倫比" },
  { id: 4161, word: "compassion", phonetic: "/kəmˈpæʃən/", partOfSpeech: "n.", meaning: "同情心", note: "show compassion：表現同情心；compassionate adj.：同情的" },
  { id: 4162, word: "compatible", phonetic: "/kəmˈpætəbəl/", partOfSpeech: "adj.", meaning: "相容的；合得來的", note: "be compatible with...；incompatible：不相容的" },
  { id: 4163, word: "compel", phonetic: "/kəmˈpel/", partOfSpeech: "vt.", meaning: "強迫", note: "force = urge" },
  { id: 4164, word: "compensate", phonetic: "/ˈkɒmpenseɪt/", partOfSpeech: "v.", meaning: "補償", note: "compensation n.：補償金；reimburse：報銷" },
  { id: 4165, word: "competence", phonetic: "/ˈkɒmpɪtəns/", partOfSpeech: "n.", meaning: "稱職的；有能力的", note: "capability = faculty = ability" },
  { id: 4166, word: "competent", phonetic: "/ˈkɒmpɪtənt/", partOfSpeech: "adj.", meaning: "有能力的；稱職的", note: "competent = capable" },
  { id: 4167, word: "complexity", phonetic: "/kəmˈpleksəti/", partOfSpeech: "n.", meaning: "複雜", note: "complex adj.：複雜的；simplicity = clarity" },
  { id: 4168, word: "complication", phonetic: "/ˌkɒmplɪˈkeɪʃən/", partOfSpeech: "n.", meaning: "複雜；感染；併發症", note: "complicate v.：複雜" },
  { id: 4169, word: "comply", phonetic: "/kəmˈplaɪ/", partOfSpeech: "vi.", meaning: "遵守", note: "comply with sth.：遵守；compliance n.：遵守" },
  { id: 4170, word: "component", phonetic: "/kəmˈpəʊnənt/", partOfSpeech: "n.", meaning: "成分；零件", note: "key / integral / essential + component：關鍵／重要的元素" },
  { id: 4171, word: "compound", phonetic: "/ˈkɒmpaʊnd/", partOfSpeech: "n.", meaning: "化合物；複合物", note: "element = part = ingredient" },
  { id: 4172, word: "comprehend", phonetic: "/ˌkɒmprɪˈhend/", partOfSpeech: "v.", meaning: "理解", note: "comprehension n.：理解；understand = grasp" },
  { id: 4173, word: "comprise", phonetic: "/kəmˈpraɪz/", partOfSpeech: "vt.", meaning: "組成；包含", note: "comprise a group / team；include = contain = encompass" },
  { id: 4174, word: "compromise", phonetic: "/ˈkɒmprəmaɪz/", partOfSpeech: "v.", meaning: "妥協；讓步", note: "one's reputation is compromised：某人聲譽受損" },
  { id: 4175, word: "compulsory", phonetic: "/kəmˈpʌlsəri/", partOfSpeech: "adj.", meaning: "義務的；強迫的", note: "mandatory = required = obligatory" },
  { id: 4176, word: "conceal", phonetic: "/kənˈsiːl/", partOfSpeech: "v.", meaning: "隱藏", note: "hide" },
  { id: 4177, word: "concede", phonetic: "/kənˈsiːd/", partOfSpeech: "v.", meaning: "承認；讓步", note: "concede sth. / that S. + V.；acknowledge = admit" },
  { id: 4178, word: "conceive", phonetic: "/kənˈsiːv/", partOfSpeech: "v.", meaning: "想像；領會；懷孕", note: "conceive of A as B：視 A 為 B；conceive (a child)：懷孕" },
  { id: 4179, word: "conception", phonetic: "/kənˈsepʃən/", partOfSpeech: "n.", meaning: "概念；受胎", note: "a conception of sth.：對某事的概念" },
  { id: 4180, word: "condemn", phonetic: "/kənˈdem/", partOfSpeech: "v.", meaning: "譴責", note: "denounce：譴責" },
  { id: 4181, word: "conduct", phonetic: "/kənˈdʌkt/", partOfSpeech: "vi.", meaning: "引導；舉辦", note: "conduct research / study / investigation / interview / survey" },
  { id: 4182, word: "confidential", phonetic: "/ˌkɒnfɪˈdenʃəl/", partOfSpeech: "adj.", meaning: "機密的", note: "off the record：非公開；public：公開的" },
  { id: 4183, word: "confine", phonetic: "/kənˈfaɪn/", partOfSpeech: "vt.", meaning: "限制；禁錮", note: "confine A to B；limit = restrain" },
  { id: 4184, word: "conform", phonetic: "/kənˈfɔːm/", partOfSpeech: "vt./vi.", meaning: "遵守；一致", note: "conform to sth.：遵守；comply with = abide by = observe = obey" },
  { id: 4185, word: "confront", phonetic: "/kənˈfrʌnt/", partOfSpeech: "vt.", meaning: "使面對；對抗", note: "confront danger：勇敢面對危險" },
  { id: 4186, word: "consecutive", phonetic: "/kənˈsekjətɪv/", partOfSpeech: "adj.", meaning: "連續；不間斷的", note: "For ... consecutive days：連續幾天" },
  { id: 4187, word: "consensus", phonetic: "/kənˈsensəs/", partOfSpeech: "n.", meaning: "共識", note: "general consensus：一致共識；reach a consensus：達成共識" },
  { id: 4188, word: "consent", phonetic: "/kənˈsent/", partOfSpeech: "v./n.", meaning: "同意", note: "consent to sth. / V.；agree：同意；refuse：拒絕" },
  { id: 4189, word: "conservation", phonetic: "/ˌkɒnsəˈveɪʃən/", partOfSpeech: "n.", meaning: "保護；節約", note: "energy / water / wildlife / environmental + conservation" },
  { id: 4190, word: "considerate", phonetic: "/kənˈsɪdərət/", partOfSpeech: "adj.", meaning: "體貼的", note: "be considerate of sb.；thoughtful = kind；inconsiderate = careless" },
  { id: 4191, word: "constitutional", phonetic: "/ˌkɒnstɪˈtjuːʃənl/", partOfSpeech: "adj.", meaning: "憲法的", note: "constitutional amendment / right：憲法修正／權利" },
  { id: 4192, word: "constraint", phonetic: "/kənˈstreɪnt/", partOfSpeech: "n.", meaning: "限制；束縛", note: "constraint on sth.：限制" },
  { id: 4193, word: "consultation", phonetic: "/ˌkɒnsəlˈteɪʃən/", partOfSpeech: "n.", meaning: "會商；諮詢", note: "be in consultation：正在商議；consultation = conference" },
  { id: 4194, word: "consumption", phonetic: "/kənˈsʌmpʃən/", partOfSpeech: "n.", meaning: "消耗；吃；喝", note: "consume v.：消耗；consumption = use" },
  { id: 4195, word: "contagious", phonetic: "/kənˈteɪdʒəs/", partOfSpeech: "adj.", meaning: "傳染性的", note: "contagious disease：傳染性疾病；infectious：傳染的" },
  { id: 4196, word: "contaminate", phonetic: "/kənˈtæmɪneɪt/", partOfSpeech: "vt.", meaning: "污染", note: "contamination n.：污染；pollute：污染" },
  { id: 4197, word: "contemplate", phonetic: "/ˈkɒntəmpleɪt/", partOfSpeech: "vt.", meaning: "深思；仔細考慮", note: "contemplate + V-ing / sth.；consider = ponder = reflect on" },
  { id: 4198, word: "contemporary", phonetic: "/kənˈtempərəri/", partOfSpeech: "adj.", meaning: "當代的；同時代的", note: "contemporary with...；modern：現代的；ancient：古代的" },
  { id: 4199, word: "contempt", phonetic: "/kənˈtempt/", partOfSpeech: "n.", meaning: "輕蔑；鄙視", note: "contempt for...：對某人或某物的鄙視" },
  { id: 4200, word: "contend", phonetic: "/kənˈtend/", partOfSpeech: "v.", meaning: "競爭；主張", note: "contend for sth.：競爭某物；contend that S. + V.：主張" },
];
